remote_theme: phish108/jekyll-bootstrap-oer

title: Bootstrap OER
description: An OER-theme for Jekyll based on Bootstrap 5

baseurl: /jekyll-bootstrap-oer

author: 
- name: Christian Glahn
  email: christian.glahn@zhaw.ch

language: de

markdown: kramdown
kramdown:
  input: GFM

ignore:
- contrib